#!/usr/bin/env python3
# tmp/context_size_test.py
import os
import sys
import shutil
from pathlib import Path

# Add project root to path to allow importing agent modules
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from worqer import qompressor, qontextor

def get_dir_size(path: Path) -> int:
    """Calculates the total character count of all files in a directory."""
    total_size = 0
    if not path.is_dir():
        return 0
    for root, _, files in os.walk(path):
        for file in files:
            file_path = Path(root) / file
            try:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    total_size += len(f.read())
            except:
                pass
    return total_size

def main():
    """
    Runs an experiment to compare the size of context generated by different
    architectural approaches.
    """
    worqspace_path = project_root / "worqspace"
    sqrapyard_path = worqspace_path / "sqrapyard"
    tmp_dir = project_root / "tmp"

    # Define paths for temporary outputs
    tmp_bloq_d = tmp_dir / "bloq.d"
    tmp_qontext_d = tmp_dir / "qontext.d"
    tmp_changed_md = tmp_dir / "changed.md"

    # Ensure tmp directories are clean
    if tmp_bloq_d.exists(): shutil.rmtree(tmp_bloq_d)
    if tmp_qontext_d.exists(): shutil.rmtree(tmp_qontext_d)
    tmp_bloq_d.mkdir()
    tmp_qontext_d.mkdir()

    print("--- Context Size Comparison Test ---")
    print(f"Source code location: {sqrapyard_path}")

    # --- 1. Baseline Scenario: Full Code ---
    print("\n[1/3] Calculating size of full source code (Baseline)...")
    baseline_size = get_dir_size(sqrapyard_path)
    if baseline_size == 0:
        print("  - ERROR: sqrapyard is empty. The test cannot produce meaningful results.")
        return
    else:
        print(f"  - Total characters (full code): {baseline_size:,}")

    # --- 2. Qompressor Scenario: Skeleton Code ---
    print("\n[2/3] Running Qompressor to generate 'bloq.d' skeletons...")
    original_argv = sys.argv
    sys.argv = ["", str(sqrapyard_path), str(tmp_bloq_d)]
    try:
        qompressor.main()
    except SystemExit:
        pass # Prevent exit
    finally:
        sys.argv = original_argv
    
    bloq_size = get_dir_size(tmp_bloq_d)
    print(f"  - Total characters (skeleton code): {bloq_size:,}")
    if baseline_size > 0:
        reduction_bloq = 100 * (1 - (bloq_size / baseline_size))
        print(f"  - Reduction vs. Baseline: {reduction_bloq:.2f}%")

    # --- 3. Qontextor Scenario: AI Summaries ---
    print("\n[3/3] Running Qontextor to generate 'qontext.d' summaries...")
    
    changed_files_list = []
    for root, _, files in os.walk(sqrapyard_path):
        for file in files:
            rel_path = (Path(root) / file).relative_to(sqrapyard_path)
            changed_files_list.append(f"- `{rel_path}`")
    
    with open(tmp_changed_md, 'w') as f:
        f.write("# Changed Files\n\n" + "\n".join(changed_files_list))

    original_argv = sys.argv
    original_cwd = os.getcwd()
    os.chdir(worqspace_path) # Qontextor needs to run from worqspace to find config

    sys.argv = ["", str(tmp_changed_md), str(tmp_qontext_d)]
    try:
        qontextor.main()
    except SystemExit:
        pass # Prevent exit
    finally:
        sys.argv = original_argv
        os.chdir(original_cwd)

    qontext_size = get_dir_size(tmp_qontext_d)
    print(f"  - Total characters (AI summaries): {qontext_size:,}")
    if baseline_size > 0:
        reduction_qontext = 100 * (1 - (qontext_size / baseline_size))
        print(f"  - Reduction vs. Baseline: {reduction_qontext:.2f}%")
    
    # --- Cleanup ---
    shutil.rmtree(tmp_bloq_d)
    shutil.rmtree(tmp_qontext_d)
    os.remove(tmp_changed_md)

    print("\n--- Test Complete ---")

if __name__ == "__main__":
    main()
